options-generated
defaultDate: aDateyyyyOrmm1OrddOrNumberOrString
	"Set the date to display on first opening if the field is blank. Specify either an actual date via a Date object, or relative to today with a number (e.g. +7) or a string of values and periods ('y' for years, 'm' for months, 'w' for weeks, 'd' for days, e.g. '+1m +7d'), or null for today."
	
	self optionAt: 'defaultDate' put: aDateyyyyOrmm1OrddOrNumberOrString