styles
defaultCss
	^ super defaultCss,
	'.ui-effects-transfer {border:1px solid black;background:#ffffe0;opacity:.5;}
	#content .main .blue { background: #77f; }
	#content .main .highlight { background:yellow; }
	#content .main .blackBorder { border:5px solid black }
	#content .main .outer { width: 104px; height: 104px; position: relative;float:left }
	#content .main .target {margin-left: 10px; width: 50px; height: 50px; position: relative; float:left;background-color: #ffa; border:1px solid black }
	#content .main .inner { width: 100px; height: 100px; background-color: #68bfef; border: 2px solid #0090df;float:left }
	#content .main .cl {clear:both;padding-top:6px}
	#content .main .link {padding-right:4px}
'