uploaded
defaultUiCss
	^ '/* colors */
.blue { background-color: #68bfef; border: 2px solid #0090df; }
.red { background-color: #ef2929; border: 2px solid #cc0000; }
.green { background-color: #72d216; border: 2px solid #4e9a06; }
.brown { background-color: #e9b96e; border: 2px solid #c17d11; }

/* box */
.pack { position: relative; height: 110px; }
.box { float: left; width: 100px; height: 100px; margin-right: 1em; }

/* actions */
.actions a { padding-right: 0.5em; }

/* icons */
ul#icons {margin:0;padding:0}

ul#icons li {
	cursor:pointer;
	float:left;
	list-style-image:none;
	list-style-position:outside;
	list-style-type:none;
	margin:2px;
	padding:4px 0pt;
	position:relative}'
