rendering
renderContentOn: html
	html heading level: 1; with: 'Hello Seaside'.
	html paragraph: 'Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar.'.
	html heading level: 2; with: 'Hello Seaside'.
	html paragraph: 'Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar. Lorem ipsum salar.'.
	
