initialization
initialize
	self initializeAttributeSelectors.
	self initializeBraceSelectors.
	self initializeBrushSelectors.
	self initializeDeprecatedClasses.
	self initializeDeprecatedSelectors.
	self initializeCallbackSelectors.
	self initializeForbiddenCallbackSelectors.
	self initializeForbiddenRenderingSelectors.
	self initializeNotPortableSelectors.
	self initializeNotPortableClasses.
	self initializeSuperSelectors