accessing-styles
toolsCss
	^ '.tool strong {
	color: #444444;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 12px;
	margin: 2px
}

.tool a, .tool a:link, .tool a:active, .tool a:visited, .tool a:focus, .tool a:hover {
	color:#008AFF;
	font-family: Helvetica, Verdana, Arial, sans-serif;
	font-size: 12px;
}

.tool table {
	border-collapse:collapse;
}

.tool table td {
	font: 10pt Verdana, Arial, Helvetica, sans-serif;
	padding-left: 5px;
	padding-right: 5px;
}
	
.tool .right {
	text-align: right;
}'