styles
carouselComponentCss
^'.carouselComponent {position:relative;border:1px solid #ccc;overflow:hidden}
 .carouselComponent .carousel-list-h {width:5000px;
		position:relative;
		z-index:1}
 .carouselComponent .carousel-list-v {height:5000px;
		position:relative;
		z-index:1}
 .carouselComponent .carousel-element {
		list-style:none;
		overflow:hidden	}
.carousel-float-h {float:left}
.carousel-float-v {float:none}
  .carouselComponent .clip-region { border:1px dotted #ccc;
		overflow:hidden;
		margin:0px auto;
		position:relative; 
	}'