styles
carouselComponentCss
^'.carouselComponent {position:relative;border:1px solid #ccc;overflow:hidden}
 .carouselComponent .carousel-list {width:5000px;
		position:relative;
		z-index:1}
 .carouselComponent .carousel-element { 
		float:left;
		list-style:none;
		overflow:hidden	}
 .carouselComponent .carousel-vertical li { 
		float:none;
		margin-bottom:0px;
		overflow:hidden;
		display:block}
 .carouselComponent ul.carousel-vertical {}
 .carouselComponent .clip-region { border:1px dotted #ccc;
		overflow:hidden;
		margin:0px auto;
		float:left;
		position:relative; 
	}'