styles
contentPaneCss
	^ '.contentPane .title {background:#e0e0e0;border-bottom-color:black;border-bottom-style:dotted;border-bottom-width:1px}
	.contentPane {width:100%}
	.contentPane .main {border:1px solid #ccc;}
	.contentPane .body {background:white}
	.contentPane .closed {height:0px}
	.contentPane a.title {	outline: none;
					padding: 0.25em;
					display: block;
					text-decoration:none;
					color:black}
	'