styles
scrollPaneCss
	^ '.scrollPane .nav {position:relative;padding:0px;border:1px solid #ccc;width:240px;height:100%}
	.scrollPane .inner {position:relative;margin:2px;overflow:hidden}
	.scrollPane .move {background:white;position:relative;top:0;left:0}
	.scrollPane .title {font-size:11px;border:1px solid #ccc;background:#e0e0e0;padding:2px}
	.scrollPane .element {font-size:10px;font-family:verdana;}
	' 