accessing
style
	^ '.drag { width: 100px; height: 100px; float: left; margin-right: 2em; }
.blue { background-color: #68bfef; border: 2px solid #0090df; }
.red { background-color: #ef2929; border: 2px solid #cc0000; }
.green { background-color: #72d216; border: 2px solid #4e9a06; } 
.clear { clear: both; height: 2em; }
.drop { background-color: #e9b96e; border: 2px solid #c17d11; min-height: 2em; }
.drop-active { border-style: dashed; }
.drop-hover { border-style: dotted; }'