options
modal: aBoolean
	"When ''modal'' is set to ''true'' the dialog will have modal behavior; other items on the page will be disabled (i.e. cannot be interacted with). Modal dialogs create an overlay below the dialog but above other page elements. Custom style values for the overlay (e.g. changing its color or opacity) can be provided with the ''overlay'' option."

	self optionAt: 'modal' put: aBoolean