accessing
welcomeCss	^ '
body{
	border:0 none;
	margin:0;
	padding:0;
}	
	
.content {
	margin: 10px;
}

.header {
	background: #DCEBED;
	height: 50px;
}

.headerImage {
	float:left;
}

.headerText {
	padding: 10px;
}

.introText {
	margin-top: 20px;
}

a img {
	border: none;
}

.introTable {
	border-spacing:0 5px;
	padding: 0;
	border-collapse: separate;
}


.introTable td {
	vertical-align: top;
	width:320px;
}


.box {
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
	background:#F0F0E7;
	padding: 10px;
	margin-bottom: 10px;
}

.example {
	width: 630px;
	padding: 10px;
	background: #F9F9F9;
	border: 1px solid #93BDD5;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
}

.seasideExample {
	background-color: #FBFFFA;
	border: 1px solid #93BDD5;
	margin: 1em;
	padding: 1em;
}

pre.codeSample {
	margin: 2em;
}

.sampleValue {
	color: #aaaaaa;
}

'