packages
javascriptPackages

	^OrderedCollection new
		add: seaside29 -> 'Javascript-Core-lr.51.mcz';
		add: seaside29 -> 'Javascript-Squeak-Core-lr.8.mcz';
		add: seaside29 -> 'Javascript-Tests-Core-lr.36.mcz';

		add: seaside29 -> 'JQuery-Core-lr.67.mcz';
		add: seaside29 -> 'JQuery-Tests-Core-lr.80.mcz';
		add: seaside29 -> 'JQuery-UI-lr.34.mcz';
		add: seaside29 -> 'JQuery-Tests-UI-lr.48.mcz';
		yourself.