packages
javascriptPackages

	^OrderedCollection new
		add: seaside29 -> 'Javascript-Core-lr.52.mcz';
		add: seaside29 -> 'Javascript-Squeak-Core-lr.8.mcz';
		add: seaside29 -> 'Javascript-Tests-Core-mls.38.mcz';

		add: seaside29 -> 'JQuery-Core-lr.69.mcz';
		add: seaside29 -> 'JQuery-Tests-Core-lr.81.mcz';
		add: seaside29 -> 'JQuery-UI-lr.35.mcz';
		add: seaside29 -> 'JQuery-Tests-UI-lr.49.mcz';
		yourself.