packages
scriptaculousPackages

	^OrderedCollection new
		add: seaside29 -> 'Prototype-Core-lr.3.mcz';
		add: seaside29 -> 'Prototype-Tests-Core-obi.2.mcz';
		add: seaside29 -> 'Scriptaculous-Core-lr.86.mcz';
		add: seaside29 -> 'Scriptaculous-Tests-Core-lr.31.mcz';
		add: seaside29 -> 'Scriptaculous-Components-lr.83.mcz';
		add: seaside29 -> 'Scriptaculous-Tests-Components-lr.22.mcz';
		yourself.