SystemOrganization addCategory: #'Scriptaculous-Core'!
SystemOrganization addCategory: #'Scriptaculous-Core-Decoration'!
SystemOrganization addCategory: #'Scriptaculous-Core-Ajax'!
SystemOrganization addCategory: #'Scriptaculous-Core-Elements'!
SystemOrganization addCategory: #'Scriptaculous-Core-Dragging'!
SystemOrganization addCategory: #'Scriptaculous-Core-Controls'!
SystemOrganization addCategory: #'Scriptaculous-Core-Components'!
