rendering
style
	^ '#ui-datepicker-div a { color: #222; cursor: pointer; }
#ui-datepicker-div { padding: 2px; z-index: 9999; border: 2px solid #bbb; background-color: #eee; }
#ui-datepicker-div .ui-datepicker-control,
#ui-datepicker-div .ui-datepicker-current { display: none; }
#ui-datepicker-div .ui-datepicker-prev { position: absolute; left: 4px; line-height: 2; }
#ui-datepicker-div .ui-datepicker-next { position: absolute; right: 4px; line-height: 2; }
#ui-datepicker-div .ui-datepicker-header { margin: 0 3.2em; text-align: center; line-height: 2; height: 2em; overflow: hidden; }

#ui-datepicker-div td { width: 2.5em; height: 2.5em; line-height: 2.5em; text-align: center; padding: 2px; }
#ui-datepicker-div tr.ui-datepicker-title-row td a { display: block; background-color: #bbb; }
#ui-datepicker-div tr.ui-datepicker-days-row td a { display: block; background-color: #ddd; }
#ui-datepicker-div tr.ui-datepicker-days-row td.ui-datepicker-current-day a { background-color: #ffbc85; }'