rendering
style
	^'
.WADeprecation strong {
	color: #444444;
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: 14px;
	margin: 2px }

.WADeprecation a {
	color:#008AFF;
	font-family: Helvetica, Verdana, Arial, sans-serif;
	font-size: 12px }

.WADeprecation table {border-collapse:collapse}

.WADeprecation td {
	font: 10pt Verdana, Arial, Helvetica, sans-serif;
	padding-left: 5px;
	padding-right: 5px }
'
	